### ISSUE TITLE
Transaction Logs parameters naming

### ISSUE THREAD

**Issue by artemistomaras** [pipermerriam/ethereum-tester#20]
I am using this package in conjunction with:
web3==3.15.0
ethereum==1.6.1

When I create a transaction that has a log, the log has the following structure:
`[AttributeDict({'block_hash': ... , transaction_hash: ..., log_index: ... })]`

When I retrieve a transaction log from an existing HTTPProvider instance, the log has this structure:
`[AttributeDict({'blockHash': ... , transactionHash: ..., logIndex: ... })]`

Therefore, when I try to call `from web3.utils.events.get_event_data` it fails with the following error:
`Traceback (most recent call last):
  File "/home/artemis/Documents/LiClipse_Workspace/django-ethereum-events/django_ethereum_events/decoder.py", line 39, in decode_logs
    decoded.append(self.decode_log(log))
  File "/home/artemis/Documents/LiClipse_Workspace/django-ethereum-events/django_ethereum_events/decoder.py", line 33, in decode_log
    return log_topic, get_event_data(self.topics_map[log_topic]['EVENT_ABI'], log)
  File "/home/artemis/.virtualenvs/django_ethereum_events/lib/python3.5/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/artemis/.virtualenvs/django_ethereum_events/lib/python3.5/site-packages/web3/utils/events.py", line 201, in get_event_data
    'logIndex': log_entry['logIndex'],
  File "/home/artemis/.virtualenvs/django_ethereum_events/lib/python3.5/site-packages/web3/utils/datastructures.py", line 25, in __getitem__
    return self.__dict__[key]
KeyError: 'logIndex'
`

**Comment by pipermerriam** [comment]
Replaced with https://github.com/pipermerriam/web3.py/issues/325 as this needs to be fixed in the web3 codebase.
